services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - guapante-db-data:/var/lib/postgresql/data
      - ./init-data:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8070:8069"
    volumes:
      - ./theme_guapante:/mnt/extra-addons/theme_guapante
      - ./enterprise:/mnt/enterprise
      - ./odoo-entrypoint.sh:/odoo-entrypoint.sh:ro
      - ./init-data/filestore:/var/lib/odoo/filestore/guapante
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    entrypoint: ["/odoo-entrypoint.sh"]
    command: -- --addons-path=/mnt/extra-addons,/mnt/enterprise,/usr/lib/python3/dist-packages/odoo/addons

volumes:
  guapante-db-data:
  odoo-web-data:
